# Generated by Django 5.2.16 on 2026-07-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_conversation_order_alter_conversation_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='conversation',
        ),
    ]
