# Generated by Django 6.0.3 on 2026-07-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_amount_order_carrier_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('aproved', 'Aproved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
