# Generated by Django 5.2.16 on 2026-07-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_created_at_alter_refundrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='decription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('aproved', 'Aproved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
