# Generated by Django 5.2.16 on 2026-07-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_decription_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('aproved', 'Aproved'), ('denied', 'Denied'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
