# Generated by Django 5.2.16 on 2026-07-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_refundrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('aproved', 'Aproved'), ('denied', 'Denied')], default='pending', max_length=20),
        ),
    ]
