# Generated by Django 5.2.16 on 2026-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_refundrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='status',
            field=models.CharField(choices=[('denied', 'Denied'), ('aproved', 'Aproved'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
    ]
